spring:
  profiles:
    active: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/app_store?useUnicode=true&amp;characterEncoding=utf-8
      username: develop
      password: develop123.
      sql-script-encoding: utf-8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true